---
- hosts: workers
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy:
      src: token/{{token_file}}
      dest: "{{token_file}}"

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat join_token | tail -2 > out.sh
     sh out.sh
