---
- hosts: masters
  become: yes
  vars_files:
    - env_variables
  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull

    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Initializing Kubernetes cluster
      shell: kubeadm init --pod-network-cidr={{cidr_v}}
      register: output

    - name: Storing Logs and Generated token for future purpose.
      local_action: copy content={{ output.stdout }} dest={{ token_file }}
      sudo: False

    - name: create .kube directory
      become: yes
      become_user: ubuntu
        file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install Network Add-on
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
